---
title: "singleRcapture: An R Package for Single-Source Capture-Recapture Models"
type: "article"
author: "Chlebicki & Beręsewicz"
year: "2025"
publication: "Submitted"
preprint: "https://arxiv.org/abs/2411.11032"
materials: "https://github.com/ncn-foreigners/paper-singleRcapture"
toc: false
categories:
  - article
  - preprint
  - population size estimation
---

## Abstract

Population size estimation is a major challenge in official statistics, social sciences, and natural sciences. The problem can be tackled by applying capture-recapture methods, which vary depending on the number of sources used, particularly on whether a single or multiple sources are involved. This paper focuses on the first group of methods and introduces a novel R package: singleRcapture. The package implements state-of-the-art single-source capture-recapture (SSCR) models (e.g.~zero-truncated one-inflated regression) together with new developments proposed by the authors, and provides a user-friendly application programming interface (API). This self-contained package can be used to produce point estimates and their variance and implements several bootstrap variance estimators or diagnostics to assess quality and conduct sensitivity analysis. It is intended for users interested in estimating the size of populations, particularly those that are difficult to reach or measure, for which information is available only from one source and dual/multiple system estimation is not applicable. Our package serves to bridge a significant gap, as the SSCR methods are either not available at all or are only partially implemented in existing R packages and other open-source software.

## Citation

> Chlebicki, P. & Beręsewicz, M. (2025). singleRcapture: An R Package for Single-Source Capture-Recapture Models,
> *Submitted to Journal of Statistical Software*

## BibTeX

``` tex
@misc{chlebicki2025singlercapture,
      title={singleRcapture: An R Package for Single-Source Capture-Recapture Models}, 
      author={Piotr Chlebicki and Maciej Beręsewicz},
      year={2025},
      eprint={2411.11032},
      archivePrefix={arXiv},
      primaryClass={stat.AP},
      url={https://arxiv.org/abs/2411.11032}, 
}
```
